services:
  users-api:
    container_name: users-api
    image: milton87/users-api:1.0.0
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@user_db:5432/postgres?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - user_db
  user_db:
    container_name: user_db
    image: postgres:17.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: {}